### ISSUE TITLE
ADD CODE OF CONDUCT to governance documentation

### ISSUE THREAD

**Issue by lwasser** [pyOpenSci/governance#29]
Right now the code of conduct is in the peer review guide. it would fit better in the governance section

[Below is the text from the peer review guide that is already published here. ](https://www.pyopensci.org/peer-review-guide/about-peer-review/code-of-conduct.html)

Tasks for this pr include
- [x]  REMOVE THE FILE FORM THE PEER REVIEW GUIDE
- [ ] MOVE TO GOVERNANCE
- [x]  ADD A REDIRECT ON pyopensci.org from https://www.pyopensci.org/peer-review-guide/about-peer-review/code-of-conduct.html to https://www.pyopensci.org/governance/code-of-conduct
    * PR here to redirect: https://github.com/pyOpenSci/pyopensci.github.io/pull/128 
 
# Community Code of Conduct

We keep our Code of Conduct in our governance documentation. [Click here to 
go there now.](https://www.pyopensci.org/governance/code-of-conduct)  

## TODO: Move this to governance

- We are committed to providing a friendly, safe and welcoming environment for all, regardless of gender, sexual orientation, disability, ethnicity, religion, or similar personal characteristic.
- Please avoid using openly sexual nicknames or other nicknames that might detract from a friendly, safe and welcoming environment for all.
- Please be kind and courteous. There’s no need to be mean or rude.
- Respect that people have differences of opinion and that every design or implementation choice carries a trade-off and numerous costs. There is seldom a right answer.
- Please keep unstructured critique to a minimum. If you have solid ideas you want to experiment with, make a fork and see how it works.
- We will exclude you from interaction if you insult, demean or harass anyone. That is not welcome behavior. We interpret the term “harassment” as including the definition in the Citizen Code of Conduct; if you have any lack of clarity about what might be included in that concept, please read their definition. In particular, we don’t tolerate behavior that excludes people in socially marginalized groups.
- Private harassment is also unacceptable. No matter who you are, if you feel you have been or are being harassed or made uncomfortable by a community member, please contact us at leah at pyopensci dot org immediately with a capture (log, photo, email) of the harassment if possible. Whether you’re a regular contributor or a newcomer, we care about making this community a safe place for you and we’ve got your back.
- Likewise, any spamming, trolling, flaming, baiting or other attention-stealing behavior are not welcome.
- Avoid the use of personal pronouns in code comments or documentation. There is no need to address persons when explaining code (e.g. “When the developer”). The focus should be on the code, not the author.

**Comment by lwasser** [comment]
@all-contributors please add @tracykteal and @lwasser for code, review, design

**Comment by lwasser** [comment]
@all-contributors please add @lwasser, @kcranston  for code, review, design

**Comment by lwasser** [comment]
closed via #31 !! 

@all-contributors please add @lwasser for code, review, design
